logging:
  level:
    root: debug

server:
  port: 6522


zuul:
  routes:
    service-a:
      path: /service-a/**
      service-id: service-a
    service-b:
      path: /service-b/**
      service-id: service-b